### PR TITLE
Add simple support for dependent python modules

### PR DESCRIPTION
**Pull request by lufinkey**
- use `prepare` script in `package.json` to install python dependencies in a `py_modules` folder
- append `py_modules` to `PYTHONPATH` at the beginning of `main.py` to allow dependencies

### CODE REVIEW

**Comment by AAGaming00** [comment]
@TrainDoctor this needs py_modules folder to be included in plugins sent to the store

**Comment by TrainDoctor** [comment]
> @TrainDoctor this needs py_modules folder to be included in plugins sent to the store

Good point, I'll add an issue asap.

**Comment by danepowell** [comment]
I'm confused, it appears this was merged to `main` but I see no evidence of it in the commit history. Was it removed via a force-push at some point? If so, why? What's the correct way to ship Python dependencies with our plugin now?

**Comment by TrainDoctor** [comment]
> I'm confused, it appears this was merged to `main` but I see no evidence of it in the commit history. Was it removed via a force-push at some point? If so, why? What's the correct way to ship Python dependencies with our plugin now?

This was merged in error. Right now the defaults folder is the recommended method. We are discussing on other methods.

**Comment by lufinkey** [comment]
> I'm confused, it appears this was merged to `main` but I see no evidence of it in the commit history. Was it removed via a force-push at some point? If so, why? What's the correct way to ship Python dependencies with our plugin now?

I was pretty confused about this decision too, since the defaults folder is more for configs than libraries. Luckily you can still manually do it the simpler way via package.json. There's an example of this in [my repo](https://github.com/lufinkey/chromecast-decky-plugin).

**Comment by TrainDoctor** [comment]
> > I'm confused, it appears this was merged to `main` but I see no evidence of it in the commit history. Was it removed via a force-push at some point? If so, why? What's the correct way to ship Python dependencies with our plugin now?
> 
> I was pretty confused about this decision too, since the defaults folder is more for configs than libraries. Luckily you can still manually do it the simpler way via package.json. There's an example of this in [my repo](https://github.com/lufinkey/chromecast-decky-plugin).

The short and sweet of it is that the js/ts scripting logic does not download pip in the CI and thus this would not work and will not be made too work as those environments are intentionally isolated during the build process using the CLI tool and the CI.

**Comment by danepowell** [comment]
@lufinkey thanks, but it seems like your project doesn't have a mechanism (at least not documented) to actually package / deploy python modules? It looks like it doesn't even use the Decky CLI.

At any rate, I [took inspiration from your project to add py_modules to the system path in main.py](https://github.com/lufinkey/chromecast-decky-plugin/blob/main/main.py#L4). Then by placing py_modules in the default directory and symlinking it from the project root, the Decky CLI seemed to magically discover, package, and ship it with the project. I know this behavior is documented in the wiki, but it's so weird and magical that I didn't believe it would work :smile: 

Assuming this is the intended workflow, seems like the Decky plugin template should add `py_modules` to the system path in main.py and maybe move the py_modules directory and set up symlinks so they work OOTB.

**Comment by danepowell** [comment]
Here's my WIP for reference: https://github.com/danepowell/decky-mqtt

**Pull request merged**
