### PR TITLE
Feature add styled components

### PR DESCRIPTION
**Pull request by devnoot**
* Adds support for styled components using [styled-components](https://styled-components.com).
* Adds an example styled component at `src/StyledComponent.tsx`

### CODE REVIEW

**Comment by TrainDoctor** [comment]
Marking this one as under consideration as I'm not sure we want to add more dependencies but this definitely seems like a great idea. I'll need @AAGaming00 to weigh in.

**Comment by AAGaming00** [comment]
There is no point in including this in the template IMO as it's usage does not differ from normal styled-components usage, and if it works by injecting a css style it may cause issues if the plugin reloads.

**Comment by devnoot** [comment]
@AAGaming00  I agree about not adding useless dependencies, but with that said is there a supported way that CSS should be added to the plugin? 

I tried editing the rollup config to support CSS, but it just generates it into `index.css`, which to my understanding can't be included. 

If there's a way to get rollup to work, I'd happily issue a PR for it.

**Comment by AAGaming00** [comment]
Making rollup css support work would require a custom css rollup loader, I already made one for another project of mine that I plan to port eventually.

**Pull request closed without merging**
